name: Build-Push to Docker Hub
on:
  push:
  workflow_dispatch:
    inputs:
      dockerfile:
        description: Dockerfile path
        required: true
        default: ./Dockerfile
      image:
        description: Image name
        required: true
        default: culturecloud/streamgram
      tag:
        description: Image tag
        required: true
        default: latest
env:
  IMAGE: ${{ inputs.image }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: pseudokawaii
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build & Push
        uses: docker/build-push-action@v4.0.0
        with:
          context: ./
          file: ${{ inputs.dockerfile }}
          platforms: linux/amd64
          push: true
          tags: |
            ${{ inputs.image }}:${{ inputs.tag }}
